spring:
  datasource:
    url: jdbc:mysql://10.132.54.169:3305/javaee_program
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 741221
  mail:
    host: smtp.qq.com
    username: 2607038766@qq.com
    password: orzurvazfjxaebba
    port: 25
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  neo4j:
    uri: bolt://10.132.54.169:7687
    authentication:
      username: neo4j
      password: 12345678
  elasticsearch:
    username: javaeecourse
    password: 12345678
    host-and-port: localhost:9200
    http-ca:
      sha256-fingerprint:
        89:26:C3:E6:09:BF:4F:8A:6C:DE:3E:3E:33:DA:01:5F:60:9D:5A:F4:ED:41:50:38:38:0F:23:77:24:D9:9E:A1
    path-prefix: learneur

server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: ignored # not update if null

jwt:
  secret: f7558b981defc498a41bb5ef6288b82d6355a8135c067e1f2fbd7b43fb9e7ea4203870a7de0abd34d388710ea6032d5b249c24b4f563f25141f32b50f4f4be3c

time:
  cron: 0 1 22 * * ?

resource:
  lesson: 1

elasticsearch:
  query:
    match-specific-type-resource:
      '{
        "bool": {
          "filter": { "term": { "resource_type": "?0" } },
          "should": [
            { "term": { "name.keyword": { "value": "?1", "boost": 100 } } },
            { "match": { "name": "?1" } },
            { "match": { "description": "?1" } }
          ]
        }
      }'
    match-all-type-resource:
      '{
        "bool": {
          "should": [
            { "term": { "name.keyword": { "value": "?0", "boost": 100 } } },
            { "match": { "name": "?0" } },
            { "match": { "description": "?0" } }
          ]
        }
      }'
    match-knowledge:
      '{
        "bool": {
          "should": [
            { "term": { "name.keyword": { "value": "?0", "boost": 100 } } },
            { "match": { "name": { "query": "?0", "boost": 2.5 } } },
            { "match": { "description": { "query": "?0", "boost": 2.5 } } },
            { "match": { "resources_description": { "query": "?0", "boost": 1.0 } } }
          ]
        }
      }'