spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learneur
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: j1101714214
  mail:
    host: stmp.qq.com
    username: 2607038766@qq.com
    password: orzurvazfjxaebba
    port: 456
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: ignored # not update if null

jwt:
  secret: f7558b981defc498a41bb5ef6288b82d6355a8135c067e1f2fbd7b43fb9e7ea4203870a7de0abd34d388710ea6032d5b249c24b4f563f25141f32b50f4f4be3c
